# ---------------------------------
# -------- Crystal Backend --------
# ---------------------------------
require "../../build_options"
require "../shared/helpers"
require "../shared/program_serializer"

module Dragonstone
    module Core
        module Compiler
            module Targets
                module Crystal
                    class Backend
                        EXTENSION = "cr"

                        def build(program : ::Dragonstone::IR::Program, options : BuildOptions) : BuildArtifact
                            serializer = Shared::ProgramSerializer.new(program)
                            source_dump = serializer.source
                            metadata = serializer.to_json
                            summary_lines = serializer.summary_lines

                            artifact_path = Shared.artifact_path(options, EXTENSION)
                            File.write(artifact_path, build_content(source_dump, summary_lines, metadata))
                            BuildArtifact.new(target: Target::Crystal, object_path: artifact_path)
                        end

                        private def build_content(source : String, summary_lines : Array(String), metadata : String) : String
                            String.build do |io|
                                io << "# Auto-generated by Dragonstone Core Compiler\n"
                                io << "module Dragonstone\n"
                                io << "  module Generated\n"
                                io << "    SOURCE = <<-'DRAGONSTONE'\n"
                                io << "#{source}\n"
                                io << "DRAGONSTONE\n\n"
                                io << "    METADATA = <<-'JSON'\n"
                                io << "#{metadata}\n"
                                io << "JSON\n\n"
                                io << "    SUMMARY = [\n"
                                summary_lines.each do |line|
                                    io << "      #{line.inspect},\n"
                                end
                                io << "    ]\n\n"
                                io << "    def self.emit(io : IO = STDOUT)\n"
                                io << "      io.puts \"=== Dragonstone program (Crystal target stub) ===\"\n"
                                io << "      io.puts SOURCE\n"
                                io << "      io.puts \"=== IR metadata ===\"\n"
                                io << "      io.puts METADATA\n"
                                io << "      io.puts \"=== Summary ===\"\n"
                                io << "      SUMMARY.each { |line| io.puts \" - \#{line}\" }\n"
                                io << "    end\n"
                                io << "  end\n"
                                io << "end\n\n"
                                io << "Dragonstone::Generated.emit\n"
                            end
                        end
                    end
                end
            end
        end
    end
end
